restore yazi configs

diff --git a/dot_profile b/dot_profile
--- a/dot_profile
+++ b/dot_profile
@@ -86,18 +86,18 @@ prepend_paths \
 lfcd() {
 	cd "$(command lf -print-last-dir "$@")" || return
 }
-# y() {
-# 	if ! command -v yazi >/dev/null 2>&1; then
-# 		echo "yazi: command not found" >&2
-# 		return 127
-# 	fi
-# 	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
-# 	yazi "$@" --cwd-file="$tmp" 2>/dev/null
-# 	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
-# 		builtin cd -- "$cwd"
-# 	fi
-# 	rm -f -- "$tmp"
-# }
+y() {
+	if ! command -v yazi >/dev/null 2>&1; then
+		echo "yazi: command not found" >&2
+		return 127
+	fi
+	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
+	yazi "$@" --cwd-file="$tmp" 2>/dev/null
+	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
+		builtin cd -- "$cwd"
+	fi
+	rm -f -- "$tmp"
+}
 codeat() {
 	code "${1:-.}" -r
 }
